// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAamDGXn5bYDc1cjcYLmjDoSkh08q2Vi74',
    appId: '1:594244070894:web:455118285c755c62f6b2ff',
    messagingSenderId: '594244070894',
    projectId: 'app-watchm',
    authDomain: 'app-watchm.firebaseapp.com',
    storageBucket: 'app-watchm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtIpUh3g9PYEwIRH7AB8nSBF_t8tx5Hpo',
    appId: '1:594244070894:android:aec28cfceed80bd8f6b2ff',
    messagingSenderId: '594244070894',
    projectId: 'app-watchm',
    storageBucket: 'app-watchm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8_7fbiC12xtqtnoSwK1FkJCeraNzGhD4',
    appId: '1:594244070894:ios:40457d8833c5fcecf6b2ff',
    messagingSenderId: '594244070894',
    projectId: 'app-watchm',
    storageBucket: 'app-watchm.firebasestorage.app',
    iosBundleId: 'com.example.watchm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8_7fbiC12xtqtnoSwK1FkJCeraNzGhD4',
    appId: '1:594244070894:ios:40457d8833c5fcecf6b2ff',
    messagingSenderId: '594244070894',
    projectId: 'app-watchm',
    storageBucket: 'app-watchm.firebasestorage.app',
    iosBundleId: 'com.example.watchm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAamDGXn5bYDc1cjcYLmjDoSkh08q2Vi74',
    appId: '1:594244070894:web:5d0e6768eff7b158f6b2ff',
    messagingSenderId: '594244070894',
    projectId: 'app-watchm',
    authDomain: 'app-watchm.firebaseapp.com',
    storageBucket: 'app-watchm.firebasestorage.app',
  );
}
